" http://vimdoc.sourceforge.net/htmldoc/usr_05.html
" General config 
syntax on " enable syntax highlighting

"set showmode
"set autoindent " to enable automatic indentation 
"set expandtab

"""" 
set cursorline " highlighting the current line 
set number " to showing line numbers
set relativenumber
set tabstop=4 " setting tab sise

"set textwidth=30
set ruler
set sidescroll=10
" config style


"""" Display options
set showmode
set showcmd " display an incomplete command in the lower right corner of the Vim window,

"""" Encoding
set encoding=utf-8

"""" Search
" Highlight matching search patterns
set hlsearch
" Enable incremental search
set incsearch
" Include matching uppercase words with lowercase search term
set ignorecase
" Include only uppercase words with uppercase search term
set smartcase

colorscheme monokai


set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" add all your plugins here (note older versions of Vundle
Plugin 'scrooloose/nerdtree' " file tree
" used Bundle instead of Plugin)

Plugin 'jistr/vim-nerdtree-tabs'

" ...

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


" KER_MAP
" NERDTREE
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>


nnoremap <A-F1> 1gt
nnoremap <A-F2> 2gt
nnoremap <A-F3> 3gt












